---
- name: Install GitLab Runner on Target Nodes
  hosts: cicd
  become: yes
  tasks:
    - name: Download GitLab Runner (Debian/Ubuntu)
      get_url:
        url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
        dest: /usr/local/bin/gitlab-runner
        mode: '0755'
      when: ansible_os_family == "Debian"

    - name: Download GitLab Runner (RedHat/Rocky)
      get_url:
        url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
        dest: /usr/local/bin/gitlab-runner
        mode: '0755'
      when: ansible_os_family == "RedHat"

    - name: Create gitlab-runner user
      user:
        name: gitlab-runner
        shell: /bin/bash
        create_home: yes

    - name: Add gitlab-runner to docker group
      user:
        name: gitlab-runner
        groups: docker
        append: yes

    - name: Install GitLab Runner as service
      shell: |
        gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner
      args:
        creates: /etc/systemd/system/gitlab-runner.service

    - name: Display registration instructions
      debug:
        msg: |
          GitLab Runner installed on {{ inventory_hostname }}.
          To register this runner with GitLab:
          1. Get registration token from GitLab (Settings -> CI/CD -> Runners)
          2. Run: gitlab-runner register
          3. Use URL: http://gitlab
          4. Choose executor: docker
          5. Default image: alpine:latest
